# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neaves, like on a tree of knowledge
email:
description: > # this means to ignore newlines until "baseurl:"
        Here, you can find posted, quickies of learnings, links, information, commands, code, etc.
baseurl: "/neaves" # the subpath of your site, e.g. /blog
url: "http://amol9.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: amol9

# Build settings
markdown: kramdown
